# Generated by Django 3.1.3 on 2021-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='static/uploads')),
                ('details', models.CharField(max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
