# Generated by Django 3.1.3 on 2021-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='details',
            field=models.TextField(),
        ),
    ]
