# Generated by Django 3.1.3 on 2021-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210326_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
