# Generated by Django 3.1.3 on 2021-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stories_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/uploads')),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
