# Generated by Django 3.1.3 on 2021-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210326_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
