# Generated by Django 3.1.3 on 2021-04-01 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_pic',
            new_name='ProfilePic',
        ),
    ]
