# Generated by Django 3.1.3 on 2021-04-17 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20210401_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='postedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adopt',
            name='postflag',
            field=models.BooleanField(default=False),
        ),
    ]
