# Generated by Django 3.1.3 on 2021-04-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210418_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
